## Importing Numpy Library

In [1]:
import numpy as np

In [2]:
a = [1,22,3,4,5]

## Changing List to Numpy Array

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a = np.array(a)

In [5]:
print(type(a))

<class 'numpy.ndarray'>


## For Checking the shape of the Numpy Array

In [8]:
print(a.shape)

(5,)


In [10]:
b = [(1,2,3,4,5,6),(1,2,3,4,5,6),(1,2,3,4,5,6)]
b = np.array(b)

In [12]:
print(b.shape)

(3, 6)


In [13]:
b

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

## for creating n-array with n-zeroes

In [21]:
a_zero = np.zeros((1,2))
a_zero

array([[0., 0.]])

## for creating n-array with same value

In [23]:
a_similar = np.full((2,2),5)
a_similar

array([[5, 5],
       [5, 5]])

In [30]:
a_random = np.full((2,2),np.random.rand())
a_random

array([[0.30545361, 0.30545361],
       [0.30545361, 0.30545361]])

## for creating identity matrix

In [32]:
a_identity = np.eye(4,4)
a_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Basic Numpy Operations

In [33]:
a = [14,25,456,68,345,234]
a = np.array(a)
a

array([ 14,  25, 456,  68, 345, 234])

In [58]:
#array having values at different indexes
print("value at index 2 :",a[2], " \nvalue from index 0 to 5 :",a[0:6],"\nvalue from index 6 to 2 :", a[:-1:2] )

value at index 2 : 456  
value from index 0 to 5 : [ 14  25 456  68 345 234] 
value from index 6 to 2 : [ 14 456 345]


In [85]:
a = [(1,2,3,4,0),(5,6,7,8,9),(1,3,5,7,9),(2,4,6,8,0)]
a = np.array(a)
print(a.shape)

(4, 5)


In [89]:
print(a)

[[ 1 23  3  4  0]
 [ 5  6  7  8  9]
 [ 1  3  5  7  9]
 [ 2  4  6  8  0]]


In [86]:
# searching the value in array with the help of index number
print(a[2,3],'\n',a[3,2])

7 
 6


In [87]:
# replacing a value
b = a[0,1]
a[0,1] = 23
print("previous value of a[0,1]:",b,"\ncurrent value of a[0,1]: ",a[0,1])

previous value of a[0,1]: 2 
current value of a[0,1]:  23


In [99]:
a[:,-3]

array([3, 7, 5, 6])

In [118]:
a = np.array([[2,3,4],[4,3,2]])
b = np.array([[3,4,6]])
c = np.concatenate((a,b))

In [119]:
c

array([[2, 3, 4],
       [4, 3, 2],
       [3, 4, 6]])

In [120]:
d = np.array([3,4,6])

In [122]:
d.shape # notice the difference in dimensions due to one less square bracket

(3,)

In [124]:
b.shape

(1, 3)

## Vector Arithmetic

In [125]:
x = np.array([1,2,3,4])
y = np.array([2,33,4,5])

In [126]:
print(x+y)

[ 3 35  7  9]


In [127]:
print(x*y)

[ 2 66 12 20]


In [128]:
print(x.dot(y))

100


## Matrix Arithmetic

In [150]:
x = np.matrix([[2,3],[3,4]])
y = np.matrix([[3,4],[2,3]])
print(x)

[[2 3]
 [3 4]]


In [145]:
print(x+y)

[[5 7]
 [5 7]]


In [146]:
print(x*y)

[[12 17]
 [17 24]]


In [147]:
print(x.dot(y))

[[12 17]
 [17 24]]


## Inverse and Transpose

In [151]:
from numpy.linalg import inv

In [153]:
print(x)

[[2 3]
 [3 4]]


In [156]:
x_inv = inv(x)
x_inv

matrix([[-4.,  3.],
        [ 3., -2.]])

In [160]:
y = np.eye(2,2)
y

array([[1., 0.],
       [0., 1.]])

In [161]:
y.T

array([[1., 0.],
       [0., 1.]])

In [163]:
x_inv.T

matrix([[-4.,  3.],
        [ 3., -2.]])

## Advance Maths

In [211]:
x = np.matrix([[2,3,4,3],[2,3,4,2],[2,3,4,1]])

In [212]:
x

matrix([[2, 3, 4, 3],
        [2, 3, 4, 2],
        [2, 3, 4, 1]])

In [214]:
x.reshape(6,2)

matrix([[2, 3],
        [4, 3],
        [2, 3],
        [4, 2],
        [2, 3],
        [4, 1]])

## Solving Linear Equations

In [217]:
x = np.array([[2,4,5],[3,4,5],[3,6,5]])
y = np.array([2,3,7])

In [218]:
np.linalg.solve(x,y)

array([ 1. ,  2. , -1.6])

## Basic Stats With Numpy

In [250]:
arr = [[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9]]
narr = np.array(arr)
print(arr)

[[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7], [3, 4, 5, 6, 7, 8], [4, 5, 6, 7, 8, 9]]


In [251]:
np.sum(narr)

120

In [252]:
narr.sum(axis=0)

array([10, 14, 18, 22, 26, 30])

In [253]:
narr.sum(axis=1)

array([21, 27, 33, 39])

In [254]:
narr.mean()

5.0

In [255]:
np.median(narr)

5.0

In [256]:
np.std(narr,axis=1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513])

In [257]:
np.std(narr,axis =0)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399])

In [258]:
np.percentile(narr,50,axis=1)

array([3.5, 4.5, 5.5, 6.5])

In [259]:
np.percentile(narr,75,axis=0)

array([3.25, 4.25, 5.25, 6.25, 7.25, 8.25])